# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkfactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField(blank=True, null=True)),
                ('l1b', models.IntegerField(blank=True, db_column='L1B', null=True)),
                ('r1b', models.IntegerField(blank=True, db_column='R1B', null=True)),
                ('l2b', models.IntegerField(blank=True, db_column='L2B', null=True)),
                ('r2b', models.IntegerField(blank=True, db_column='R2B', null=True)),
                ('l3b', models.IntegerField(blank=True, db_column='L3B', null=True)),
                ('r3b', models.IntegerField(blank=True, db_column='R3B', null=True)),
                ('lhr', models.IntegerField(blank=True, db_column='LHR', null=True)),
                ('rhr', models.IntegerField(blank=True, db_column='RHR', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'parkFactors',
            },
        ),
        migrations.CreateModel(
            name='Platoonbatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('home_id', models.TextField(blank=True, null=True)),
                ('playersplit', models.TextField(blank=True, null=True)),
                ('split', models.TextField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('ab', models.IntegerField(blank=True, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('doub', models.IntegerField(blank=True, null=True)),
                ('trip', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('rbi', models.IntegerField(blank=True, null=True)),
                ('sb', models.IntegerField(blank=True, null=True)),
                ('cs', models.IntegerField(blank=True, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('so', models.IntegerField(blank=True, null=True)),
                ('ba', models.FloatField(blank=True, null=True)),
                ('obp', models.FloatField(blank=True, null=True)),
                ('slg', models.FloatField(blank=True, null=True)),
                ('ops', models.FloatField(blank=True, null=True)),
                ('tb', models.IntegerField(blank=True, null=True)),
                ('gdp', models.IntegerField(blank=True, null=True)),
                ('hbp', models.IntegerField(blank=True, null=True)),
                ('babip', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'platoonBatters',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('pos_pitch', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('player_bat', models.TextField(blank=True, null=True)),
                ('player_throw', models.TextField(blank=True, null=True)),
                ('home_id', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Ratiobatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('home_id', models.TextField(blank=True, null=True)),
                ('playeryear', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('hr_rate', models.FloatField(blank=True, null=True)),
                ('so_rate', models.FloatField(blank=True, null=True)),
                ('bb_rate', models.FloatField(blank=True, null=True)),
                ('xbh_rate', models.FloatField(blank=True, null=True)),
                ('xbph_rate', models.FloatField(blank=True, null=True)),
                ('sow', models.FloatField(blank=True, null=True)),
                ('abso', models.FloatField(blank=True, null=True)),
                ('abhr', models.FloatField(blank=True, null=True)),
                ('abrbi', models.FloatField(blank=True, null=True)),
                ('gbfb', models.FloatField(blank=True, null=True)),
                ('goao', models.FloatField(blank=True, null=True)),
                ('ip_rate', models.FloatField(blank=True, null=True)),
                ('ld_rate', models.FloatField(blank=True, null=True)),
                ('hrfb', models.FloatField(blank=True, null=True)),
                ('iffb', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ratioBatters',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('league', models.TextField(blank=True, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('home_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'teams',
            },
        ),
    ]
