# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkfactors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platoonbatters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ratiobatters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
