# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statview', '0002_auto_20161007_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkfactors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='platoonbatters',
            name='id',
        ),
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='id',
        ),
        migrations.AlterField(
            model_name='parkfactors',
            name='team',
            field=models.TextField(blank=True, default='MLB', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platoonbatters',
            name='playersplit',
            field=models.TextField(blank=True, default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_id',
            field=models.IntegerField(blank=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratiobatters',
            name='playeryear',
            field=models.TextField(blank=True, default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='home_id',
            field=models.TextField(blank=True, default=None, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='ratiobatters',
            name='id',
        ),
        migrations.AlterOrderWithRespectTo(
            name='ratiobatters',
            order_with_respect_to='player_name',
        ),
    ]
